### PR TITLE
Update for django 1.11

### LINKED ISSUE #9: Django 1.11 not render widget
Widget template not rendered in Django 1.11 due to new [form rendering API](https://docs.djangoproject.com/en/1.11/releases/1.11/#template-based-widget-rendering)

### PR DESCRIPTION
**Pull request by pavillet**
Hello,

This fixes #9 at the cost of many changes.
It was tested on a live project and work as it should.

Please review and tell me if that's ok with you, accept the pull request.

### CODE REVIEW

**Comment by oscarmcm** [comment]
@pavillet thanks for your effort 🥇 pushed a new version [v2.0.0](https://github.com/oscarmcm/django-places/releases/tag/v2.0.0)

**Comment by oscarmcm** [comment]
@pavillet thanks for your effort 🥇 pushed a new version [v2.0.0](https://github.com/oscarmcm/django-places/releases/tag/v2.0.0)

**Comment by pavillet** [comment]
@oscarmcm hello do you know if the new version will be avalaible on pip sometimes ? Thank you

**Comment by oscarmcm** [comment]
@pavillet I've pushed it long time ago > https://pypi.python.org/pypi/dj-places/2.0.0

**Comment by pavillet** [comment]
@oscarmcm Yes my bad :) thank you

**Pull request merged**
